# image will be published to ghcr.io/<user>/<name>
name: auraos-core
# description will be included in the image's metadata
description: Aura's own personalised core image
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore-hci
image-version: stable-nvidia
stages:
  - name: JetBrainsMonoSlashedNerdFont
    from: fedora:42
    modules:
      - type: script
        scripts:
          - build-JetBrainsMonoSlashedNerdFont.sh
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # JetBrainsMonoSlashedNerdFont
  - type: copy
    from: JetBrainsMonoSlashedNerdFont
    src:  /tmp/usr
    dest: /usr
  - type: script
    snippets:
      - fc-cache -fv
  - type: dnf
    install:
      packages:
        - trash-cli
        - podman-docker
        - cockpit-navigator
        - cockpit-ostree
        - fastfetch
        - lsd
        - just
        - micro
        - nginx
        - zsh
        - fzf
        - zsh-autosuggestions
        - zsh-syntax-highlighting
    group-remove:
      packages:
        - moby-engine
  - from-file: common-modules.yml
  - type: script
    scripts:
      - remove-coreos-motd-spam.sh
      - atuin.sh
      - moar.sh
      - zshplugins.sh
  - type: files
    files:
      - source: system/etc/p10k
        destination: /etc/p10k
      - source: system/etc/profile.d
        destination: /etc/profile.d
      - source: system/etc/environment
        destination: /etc/enviornment
      - source: system/etc/inputrc
        destination: /etc/inputrc
      - source: system/etc/zshrc
        destination: /etc/zshrc
  - from-file: common-auto-update-reboot.yml