# image will be published to ghcr.io/<user>/<name>
name: auraos-core
# description will be included in the image's metadata
description: Aura's own personalised core image
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore-hci
image-version: stable-zfs
stages:
  - name: JetBrainsMonoSlashedNerdFont
    from: fedora:41
    modules:
      - type: script
        scripts:
          - build-JetBrainsMonoSlashedNerdFont.sh
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # JetBrainsMonoSlashedNerdFont
  - type: copy
    from: JetBrainsMonoSlashedNerdFont
    src:  /tmp/usr
    dest: /usr
  - type: script
    snippets:
      - fc-cache -fv
  - type: rpm-ostree
    install:
      - wget2
      - nginx
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
  - from-file: common-modules.yml
  - type: script
    scripts:
      - atuin.sh
      - moar.sh
      - zshplugins.sh
  - type: files
    files:
      - source: system/etc/p10k
        destination: /etc/p10k
      - source: system/etc/profile.d
        destination: /etc/profile.d
      - source: system/etc/enviornment
        destination: /etc/enviornment
      - source: system/etc/inputrc
        destination: /etc/inputrc
      - source: system/etc/zshrc
        destination: /etc/zshrc