# image will be published to ghcr.io/<user>/<name>
name: auraos-slim
# description will be included in the image's metadata
description: Aura's own personalised slim image
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: stable
stages:
  - name: JetBrainsMonoSlashedNerdFont
    from: fedora:41
    modules:
      - type: script
        scripts:
          - build-JetBrainsMonoSlashedNerdFont.sh
  - name: HeadsetControl
    from: fedora:41
    modules:
      - type: script
        scripts:
          - build-headsetcontrol.sh
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # JetBrainsMonoSlashedNerdFont
  - type: copy
    from: JetBrainsMonoSlashedNerdFont
    src:  /tmp/usr
    dest: /usr
  - type: script
    snippets:
      - fc-cache -fv
  - type: rpm-ostree
    install:
      - docker-compose
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
  - from-file: common-modules.yml
  - from-file: common-fonts.yml
  - type: script
    scripts:
      - atuin.sh
      - moar.sh
      - posy-cursors.sh
      - zshplugins.sh
      - fluent-icons.sh
  - from-file: common-files.yml