# image will be published to ghcr.io/<user>/<name>
name: auraos-thin
# description will be included in the image's metadata
description: Aura's own personalised image for thin clients
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41
stages:
  - name: JetBrainsMonoSlashedNerdFont
    from: fedora:41
    modules:
      - type: script
        scripts:
          - build-JetBrainsMonoSlashedNerdFont.sh
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # JetBrainsMonoSlashedNerdFont
  - type: copy
    from: JetBrainsMonoSlashedNerdFont
    src:  /tmp/usr
    dest: /usr
  - type: script
    snippets:
      - fc-cache -fv
  - type: rpm-ostree
    install:
      - micro
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    remove:
      - kwrite
      - kate
      - kate-plugins
      - kate-krunner-plugin
      - vim-data
      - vim-minimal
      - vim-filesystem
      - vim-common
      - vim-enhanced
      - nano
      - nano-default-editor
      - default-editor
  - from-file: common-modules.yml
  - from-file: common-fonts.yml
  - type: script
    scripts:
      - atuin.sh
      - moar.sh
      - posy-cursors.sh
      - zshplugins.sh
      - fluent-icons.sh
  - from-file: common-files.yml
  - from-file: common-topgrade.yml
  - from-file: common-auto-update-reboot.yml