# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: auraos-thin
# description will be included in the image's metadata
description: Aura's own personalised image for thin clients
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43
stages:
  - name: JetBrainsMonoSlashedNerdFont
    from: fedora:43
    modules:
      - type: script
        scripts:
          - build-JetBrainsMonoSlashedNerdFont.sh
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # JetBrainsMonoSlashedNerdFont
  - type: copy
    from: JetBrainsMonoSlashedNerdFont
    src:  /tmp/usr
    dest: /usr
  - type: script
    snippets:
      - fc-cache -fv
  - type: dnf
    install:
      packages:
        - micro
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
    remove:
      packages:
        - firefox-langpacks
        - firefox
        - kwrite
        - kate
        - kate-plugins
        - kate-krunner-plugin
        - vim-data
        - vim-minimal
        - vim-filesystem
        - vim-common
        - vim-enhanced
        - nano
        - nano-default-editor
        - default-editor
  - from-file: common-modules.yml
  - from-file: common-fonts.yml
  - type: script
    scripts:
      - atuin.sh
      - moar.sh
      - posy-cursors.sh
      - zshplugins.sh
      - fluent-icons.sh
  - from-file: common-files.yml
  - from-file: common-topgrade.yml
  - from-file: common-auto-update-reboot.yml
  - type: default-flatpaks
    configurations:
      - notify: true
        system:
          # If no repo information is specified, Flathub will be used by default
          repo:
            url: https://dl.flathub.org/repo/flathub.flatpakrepo
            name: flathub
            title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
          install:
            - org.mozilla.firefox