type: script
scripts:
  # this sets up the proper policy & signing files for signed images to work
  - signing.sh
  - atuin.sh
  - moar.sh
  - posy-cursors.sh
  - zshplugins.sh
  - fluent-icons.sh
  - xremap.sh