type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/pennbauman/ports/repo/fedora-%OS_VERSION%/pennbauman-ports-fedora-%OS_VERSION%.repo
  - https://yum.enpass.io/enpass-yum.repo
  - https://repo.vivaldi.com/stable/vivaldi-fedora.repo
  - https://raw.githubusercontent.com/AuraHerreroRuiz/auraos/live/sources/repos/insync.repo
  - https://raw.githubusercontent.com/ublue-os/bluefin/main/dx/etc/yum.repos.d/vscode.repo
install:
  - applet-window-buttons
  - code
  - ddcutil
  - enpass
  - fzf
  - vivaldi-stable
  - insync
  - insync-dolphin
  - lf
  - lsd
  - libreoffice
  - micro
  - mosquitto
  - pipx
  - bismuth
  - yakuake
  - hunspell-es
  - variety
  - krename
  - ksystemlog
  - kcm_wacomtablet
  - trash-cli
  - touchegg
  - power-profiles-daemon
  - playerctl
  - python-spotipy
  - solaar
  - terminus-fonts-console
  - pam-u2f
  - pamu2fcfg
  # zsh and its plugins
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  #Virt-manager packages from bluefin-dx
  - qemu
  - qemu-user-binfmt
  - virt-manager
  - libvirt
  - edk2-ovmf
  - genisoimage
  - qemu-img
  - qemu-system-x86-core
  - qemu-char-spice
  - qemu-device-usb-redirect
  - qemu-device-display-virtio-vga
  - qemu-device-display-virtio-gpu
  #Kup dependencies
  - par2cmdline
  - libgit2
  - python3-pyxattr
  - python3-fusepy
optfix:
  - enpass
  - vivaldi
remove:
  # Remove the native firefox (from Fedora) in favor of the Flatpak.
  - spectacle
  - firefox-langpacks
  - firefox
  - kwrite
  - kate
  - kate-plugins
  - vim-data
  - vim-minimal
  - vim-filesystem
  - vim-common
  - vim-enhanced
  - nano
  - nano-default-editor
  - default-editor
  - breeze-gtk-gtk2
  - breeze-gtk-gtk3
  - breeze-gtk-gtk4
  - kde-gtk-config